---
- name: Prepare the configuration directory
  ansible.builtin.file:
    path: ~/.config/virt-lightning
    state: directory

- name: Write the configuration file
  ansible.builtin.template:
    src: config.ini.j2
    dest: ~/.config/virt-lightning/config.ini
