---
- name: Install Ansible's virt dependencies
  become: true
  ansible.builtin.package:
    name:
      - python-libvirt
      - python-lxml

- name: Record the storage pool location
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"
  register: storage_dir
  ansible.builtin.shell: |
    ~/.local/bin/vl storage_dir

- name: Build the images
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"
  args:
    creates: "{{ storage_dir.stdout }}/upstream/centos-7.qcow2"
  ansible.builtin.shell: |
    cd ~/virt-lightning/images
    MIRROR_URL=http://192.168.123.1 ./image centos-7 download
