---
- name: Install the virt-lightning dependencies
  become: true
  ansible.builtin.package:
    name: "{{ virt_lightning_packages }}"

- name: Install git, setup.py needs it
  become: true
  ansible.builtin.package:
    name: git

- name: Install the dependencies of the Ansible modules
  become: true
  ansible.builtin.package:
    name:
      - python-libvirt
      - python-lxml
      - rsync

- name: Start libvirt
  become: true
  ansible.builtin.service:
    name: libvirtd
    state: started

- name: Add the fine users to the current users
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: "{{ virt_lightning_groups }}"
