---
- name: Gather os specific variables
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
  ansible.builtin.include_vars: "{{ item }}"

- name: Install
  ansible.builtin.import_tasks: install.yml

- name: Reset ssh connection to reload the groups
  ansible.builtin.meta: reset_connection

- name: Prepare for qemu:///system
  ansible.builtin.import_tasks: prepare_system.yml

- name: Venv
  ansible.builtin.import_tasks: venv.yml

- name: Config
  ansible.builtin.import_tasks: config.yml

- name: Prepare an image
  ansible.builtin.import_tasks: image.yml

- name: Test
  when: virt_lightning_run_tests
  ansible.builtin.import_tasks: test.yml
