---
- name: Generate a SSH key
  args:
    creates: ~/.ssh/id_rsa
  ansible.builtin.command: ssh-keygen -q -t rsa -C "" -N "" -f ~/.ssh/id_rsa

- name: Start the environment
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"
  ansible.builtin.shell: |
    set -eux
    echo $PATH
    vl distro_list > virt-lightning.yaml
    vl up
    vl ansible_inventory > inventory

- name: Install Ansible
  become: true
  ansible.builtin.package:
    name: ansible

- name: Test the new VM
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"
  ansible.builtin.shell: |
    ansible all -m shell -a "ping -c 1 google.ca" -i inventory

- name: List the VM
  register: list_vm
  ansible.builtin.command: virsh -c {{ virt_lightning_qemu_uri }} list

- name: Assert the VM is in the list
  ansible.builtin.assert:
    that:
      - "'centos' in list_vm.stdout"

- name: Destroy the environment
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"
  ansible.builtin.shell: |
    vl down

- name: List the VM
  ansible.builtin.command: virsh -c {{ virt_lightning_qemu_uri }} list
  register: list_vm
- name: Assert the VM is not in the list
  ansible.builtin.assert:
    that:
      - "'centos' not in list_vm.stdout"
