---
- name: Push the working directory
  when: dev_mode is defined
  ansible.posix.synchronize:
    src: ../../virt-lightning
    dest: ~/

- name: Fetch virt-lightning master branch
  when: dev_mode is not defined
  ansible.builtin.git:
    repo: https://github.com/virt-lightning/virt-lightning
    dest: ~/virt-lightning

- name: Pip install
  # --no-deps because of Ubuntu: https://github.com/pypa/pip/issues/4222
  ansible.builtin.command: |-
    pip3 install --no-deps --user ~/virt-lightning
